export interface RawVendor {
  name: string;
  website: string | null;
  showroomRep: string | null;
  tradeRetail: 'Trade' | 'Retail' | null;
  stockCustom: 'Stock' | 'Custom' | 'Both' | null;
  priceRange: 'Low' | 'Mid' | 'High' | null;
  offerings: string[];
  notes: string | null;
  login: string | null;
}

// Real vendor list from the firm's FF&E vendor spreadsheet
// (MDI_FFE_Vendors.xlsx) — 65 vendors, imported verbatim.
export const RAW_VENDORS: RawVendor[] = [
  { name: 'Four Hands', website: 'https://fourhands.com/', showroomRep: 'Four Hands, Vegas\nKelsie Gonzales\nkgonzales@fourhands.com', tradeRetail: 'Trade', stockCustom: 'Stock', priceRange: 'Mid', offerings: ['FURNITURE', 'OUTDOOR', 'DECOR', 'MIRRORS', 'LAMPS'], notes: null, login: 'Customer number: 132631 Password: MDIorders2021*' },
  { name: 'Verellen', website: 'https://verellen.biz/', showroomRep: 'Curate to the Trade, SLC\nAnya Dvoretskaya\nAnya@curatetothetrade.com', tradeRetail: 'Trade', stockCustom: null, priceRange: 'High', offerings: ['FURNITURE'], notes: null, login: 'No login, quotes and purchasing through Rep' },
  { name: 'Palecek', website: 'https://www.palecek.com/', showroomRep: 'Curate to the Trade, SLC\nAnya Dvoretskaya\nAnya@curatetothetrade.com', tradeRetail: 'Trade', stockCustom: null, priceRange: 'High', offerings: ['FURNITURE', 'OUTDOOR', 'DECOR', 'MIRRORS', 'LAMPS'], notes: null, login: 'Username: orders@madisonditton.com Password: MDIorders2021*' },
  { name: 'Highland House', website: 'https://www.highlandhousefurniture.com/', showroomRep: 'Curate to the Trade, SLC\nAnya Dvoretskaya\nAnya@curatetothetrade.com', tradeRetail: 'Trade', stockCustom: 'Custom', priceRange: 'High', offerings: ['FURNITURE'], notes: null, login: 'No login, quotes and purchasing through Rep' },
  { name: 'Baker McGuire', website: 'https://www.bakerfurniture.com/', showroomRep: 'Curate to the Trade, SLC\nAnya Dvoretskaya\nAnya@curatetothetrade.com', tradeRetail: 'Trade', stockCustom: null, priceRange: 'High', offerings: [], notes: null, login: 'No login, quotes and purchasing through Rep' },
  { name: 'Castelle', website: 'https://www.castellefurniture.com/', showroomRep: 'Curate to the Trade, SLC\nAnya Dvoretskaya\nAnya@curatetothetrade.com', tradeRetail: 'Trade', stockCustom: null, priceRange: null, offerings: ['OUTDOOR'], notes: null, login: 'No login, quotes and purchasing through Rep' },
  { name: 'Eichholtz', website: 'https://www.eichholtz.com/usa/', showroomRep: 'Curate to the Trade, SLC\nAnya Dvoretskaya\nAnya@curatetothetrade.com', tradeRetail: 'Trade', stockCustom: null, priceRange: 'High', offerings: ['FURNITURE', 'DECOR', 'LAMPS'], notes: null, login: 'No login, quotes and purchasing through Rep' },
  { name: 'Stone International', website: 'https://www.stoneinternational.it/en', showroomRep: 'Curate to the Trade, SLC\nAnya Dvoretskaya\nAnya@curatetothetrade.com', tradeRetail: 'Trade', stockCustom: 'Custom', priceRange: 'High', offerings: ['FURNITURE'], notes: 'Stone top tables\nItaly', login: 'No login, quotes and purchasing through Rep' },
  { name: 'Hancock & Moore', website: 'https://www.hancockandmoore.com/', showroomRep: 'Curate to the Trade, SLC\nAnya Dvoretskaya\nAnya@curatetothetrade.com', tradeRetail: 'Trade', stockCustom: 'Custom', priceRange: 'High', offerings: ['FURNITURE'], notes: 'Leather seating', login: 'No login, quotes and purchasing through Rep' },
  { name: 'Arteriors', website: 'https://www.arteriorshome.com/', showroomRep: 'High Point\nIvystone Luxe Home\nMelissa Meinzer\nmmeinzer@ivystone.com', tradeRetail: 'Trade', stockCustom: 'Stock', priceRange: 'Mid', offerings: ['FURNITURE', 'OUTDOOR', 'DECOR', 'MIRRORS'], notes: null, login: 'COME BACK TO THIS ONE AND RESET PASSWORD ORDERS@MADISONDITTON.COM' },
  { name: 'Classic Home', website: 'https://www.classichome.com/', showroomRep: 'High Point\nIvystone Luxe Home\nMelissa Meinzer\nmmeinzer@ivystone.com', tradeRetail: 'Trade', stockCustom: 'Stock', priceRange: 'Mid', offerings: ['FURNITURE'], notes: null, login: 'Email: orders@madisonditton.com - a code will be sent to this email' },
  { name: 'Villa by Classic Home', website: 'https://www.classichome.com/collections/all-villa', showroomRep: 'High Point\nIvystone Luxe Home\nMelissa Meinzer\nmmeinzer@ivystone.com', tradeRetail: 'Trade', stockCustom: 'Stock', priceRange: 'Mid', offerings: ['PILLOWS', 'BEDDING'], notes: null, login: 'Email: orders@madisonditton.com - a code will be sent to this email' },
  { name: 'Loloi', website: 'https://www.loloirugs.com/', showroomRep: 'High Point\nIvystone Luxe Home\nMelissa Meinzer\nmmeinzer@ivystone.com', tradeRetail: 'Trade', stockCustom: 'Stock', priceRange: 'Mid', offerings: ['RUGS', 'PILLOWS'], notes: 'Needs an opening order to open the account. Gives us wholesale pricing. Samples are 18x18 and ar $25 a piece including freight', login: 'APPLICATION PENDING' },
  { name: 'cFc Furniture', website: 'https://customfurniturela.com/', showroomRep: 'High Point\nIvystone Luxe Home\nMelissa Meinzer\nmmeinzer@ivystone.com', tradeRetail: 'Trade', stockCustom: null, priceRange: null, offerings: ['FURNITURE'], notes: '3k opening to keep our highest discount. 10k per year to keep account open. They\'ll customize', login: 'Username: orders@madisonditton.com Password: MDIorders2021*' },
  { name: 'Noir Furniture', website: 'https://noirfurniturela.com/', showroomRep: 'Lauren Wade\nlauren@noirfurniturela.com', tradeRetail: 'Trade', stockCustom: null, priceRange: null, offerings: ['FURNITURE'], notes: null, login: 'Username: orders@madisonditton.com Password: MDIorders2021*' },
  { name: 'Holly Hunt', website: 'https://www.hollyhunt.com/', showroomRep: 'Kneedler Fauchere, Denver\nWendy Convery\nwconvery@kneedlerfauchere.com', tradeRetail: 'Trade', stockCustom: null, priceRange: 'High', offerings: ['FURNITURE', 'OUTDOOR', 'LAMPS'], notes: null, login: 'APPLICATION PENDING' },
  { name: 'Gregorius Pineo', website: 'https://gregoriuspineo.com/', showroomRep: 'Kneedler Fauchere, Denver\nWendy Convery\nwconvery@kneedlerfauchere.com', tradeRetail: 'Trade', stockCustom: 'Custom', priceRange: 'High', offerings: ['FURNITURE', 'MIRRORS', 'LAMPS'], notes: null, login: 'Username: orders@madisonditton.com Password: MDIorders2021*' },
  { name: 'Arhaus', website: 'https://www.arhaus.com/', showroomRep: 'Park City', tradeRetail: 'Retail', stockCustom: 'Both', priceRange: 'Mid', offerings: ['FURNITURE', 'OUTDOOR'], notes: null, login: 'COME BACK TO' },
  { name: 'Caracole', website: 'https://caracole.com/', showroomRep: null, tradeRetail: 'Trade', stockCustom: null, priceRange: null, offerings: [], notes: null, login: 'COME BACK TO' },
  { name: 'Harbour', website: 'https://shopharbour.com/', showroomRep: 'Rowena, 801-636-3973', tradeRetail: null, stockCustom: 'Both', priceRange: null, offerings: ['OUTDOOR'], notes: null, login: 'PENDING ACCOUNT CREATION, UPLOAD RESALE ONCE CREATED' },
  { name: 'Bernhardt', website: 'https://www.bernhardt.com/', showroomRep: null, tradeRetail: 'Trade', stockCustom: 'Both', priceRange: 'High', offerings: ['FURNITURE', 'OUTDOOR'], notes: null, login: 'APPLICATION PENDING' },
  { name: 'Visual Comfort', website: 'https://www.visualcomfort.com/us/c/shop/lamps?tid=mm_lamps', showroomRep: null, tradeRetail: null, stockCustom: null, priceRange: null, offerings: ['LAMPS'], notes: null, login: 'Username: orders@madisonditton.com Password: MDIorders2021*' },
  { name: 'Phillips Collection', website: 'https://www.phillipscollection.com/', showroomRep: 'Robin Dorn robin@rldorn.com', tradeRetail: 'Trade', stockCustom: null, priceRange: null, offerings: ['DECOR'], notes: null, login: 'Username: orders@madisonditton.com Password: MDIorders2021*' },
  { name: 'Uttermost', website: 'https://uttermost.com/', showroomRep: null, tradeRetail: 'Trade', stockCustom: null, priceRange: null, offerings: ['DECOR', 'MIRRORS', 'LAMPS'], notes: 'Requires a $4k opening order prior to August 1, 2026 to keep account access', login: 'Username: orders@madisonditton.com Password: MDIorders2021*' },
  { name: 'Currey & Co', website: 'https://www.curreyandcompany.com/', showroomRep: 'Sales Rep: Jodie Veeder jveeder@msn.com Account Executive: Christy Weaver cweaver@curreyco.com', tradeRetail: 'Trade', stockCustom: null, priceRange: 'High', offerings: ['FURNITURE', 'OUTDOOR', 'DECOR', 'MIRRORS', 'LAMPS'], notes: 'Account number: 22368', login: 'Username: orders@madisonditton.com Password: MDIorders2021*' },
  { name: 'Cuff Studio', website: 'https://www.cuffstudio.com/', showroomRep: 'amy@cuffstudio.com', tradeRetail: 'Trade', stockCustom: 'Custom', priceRange: 'High', offerings: ['FURNITURE'], notes: 'Boutique', login: 'will send a code when orders@madisonditton.com is entered' },
  { name: 'Diamond Sofa', website: 'https://www.diamondsofa.com/', showroomRep: 'Vegas & High Point, Mark Chapman\nCell 480.250.8260\ngo2chap@cox.net', tradeRetail: 'Trade', stockCustom: null, priceRange: null, offerings: ['FURNITURE'], notes: 'Pricing list Link', login: 'No login, quotes and purchasing through Rep' },
  { name: 'Global Views (Surya Brand)', website: 'https://globalviews.surya.com/', showroomRep: 'Savannah, 470-749-9951, email savannah.scoggins@surya.com.', tradeRetail: 'Trade', stockCustom: null, priceRange: null, offerings: ['PILLOWS', 'DECOR', 'MIRRORS', 'LAMPS'], notes: 'Surya account number: 46-MADISO1', login: 'Username: orders@madisonditton.com Password: MDIorders2021*' },
  { name: 'Mitchell Gold + Bob Williams\n(MG+BW) (Surya Brand)', website: 'https://mgbw.com/', showroomRep: 'Savannah, 470-749-9951, email savannah.scoggins@surya.com.', tradeRetail: 'Trade', stockCustom: null, priceRange: null, offerings: ['FURNITURE'], notes: 'Surya ccount number 46-MADISO1', login: 'Username: orders@madisonditton.com Password: MDIorders2021*' },
  { name: 'B&B Italia', website: 'https://www.bebitalia.com/en-us/', showroomRep: 'Studio Como, SLC\nLauren Ambuhl lauren@studiocomo.com', tradeRetail: 'Trade', stockCustom: 'Custom', priceRange: 'High', offerings: [], notes: 'Italy', login: 'Username: orders@madisonditton.com Password: MDIorders2021*' },
  { name: 'Moss Home', website: 'https://mosshomeusa.com/', showroomRep: null, tradeRetail: 'Trade', stockCustom: null, priceRange: null, offerings: ['FURNITURE', 'PILLOWS'], notes: 'USA', login: 'Username: orders@madisonditton.com Password: MDIorders2021*' },
  { name: 'Rowe Home', website: 'https://www.rowefurniture.com/', showroomRep: null, tradeRetail: 'Trade', stockCustom: null, priceRange: null, offerings: [], notes: 'PENDING APPROVAL', login: 'Username: orders@madisonditton.com Password: MDIorders2021*' },
  { name: 'Soho Home', website: 'https://www.sohohome.com/us/', showroomRep: 'Samantha, ustrade@sohohome.com', tradeRetail: 'Retail', stockCustom: null, priceRange: null, offerings: ['FURNITURE', 'PILLOWS', 'MIRRORS'], notes: null, login: 'Username: orders@madisonditton.com Password: MDIorders2021*' },
  { name: 'Moe\'s Home Collection', website: 'https://www.moeshome.com/', showroomRep: 'High Point\nJeff Howard\njeffhoward9@gmail.com', tradeRetail: 'Trade', stockCustom: 'Stock', priceRange: 'Mid', offerings: ['FURNITURE'], notes: null, login: 'Username: orders@madisonditton.com Password: MDIorders2021*' },
  { name: 'Resoration Hardware', website: 'https://rh.com/us/en/', showroomRep: 'RH, SLC\nGee Pereira Oliveira\ngpereiraoliv@rh.com', tradeRetail: 'Retail', stockCustom: 'Stock', priceRange: 'High', offerings: ['FURNITURE', 'OUTDOOR', 'RUGS', 'PILLOWS', 'MIRRORS', 'LAMPS', 'BEDDING'], notes: null, login: 'Trade Number: 20211108162712 email: madison@madisonditton.com' },
  { name: 'Amara Rugs', website: 'https://www.amararugs.com/', showroomRep: null, tradeRetail: 'Trade', stockCustom: null, priceRange: null, offerings: ['RUGS'], notes: 'Material Bank, APPLICATION PENDING', login: 'Username: orders@madisonditton.com Password: MDIorders2021*' },
  { name: 'Stark', website: 'https://starkcarpet.com/?selectedbrand=stark_brand', showroomRep: 'Regency Royale, SLC', tradeRetail: null, stockCustom: null, priceRange: null, offerings: ['RUGS'], notes: null, login: 'APPLICATION PENDING' },
  { name: 'District Loom', website: 'https://www.districtloom.com/', showroomRep: null, tradeRetail: 'Retail', stockCustom: null, priceRange: null, offerings: ['RUGS'], notes: 'One of a kind vintage rugs', login: 'APPLICATION PENDING' },
  { name: 'Eliko Rugs', website: 'https://www.elikorugsbydavidariel.com/default.asp', showroomRep: 'Curate to the Trade, SLC\nAnya Dvoretskaya\nAnya@curatetothetrade.com', tradeRetail: null, stockCustom: null, priceRange: null, offerings: ['RUGS'], notes: null, login: null },
  { name: 'Exquisite Rugs', website: 'https://www.exquisiterugs.com/', showroomRep: null, tradeRetail: 'Trade', stockCustom: null, priceRange: null, offerings: ['RUGS'], notes: null, login: null },
  { name: 'Endless Knot Rugs', website: 'https://endlessknotrugs.com/', showroomRep: null, tradeRetail: 'Trade', stockCustom: null, priceRange: null, offerings: ['RUGS'], notes: 'Material Bank', login: null },
  { name: 'The Vintage Rug Shop', website: 'https://thevintagerugshop.com/', showroomRep: null, tradeRetail: 'Retail', stockCustom: null, priceRange: null, offerings: ['RUGS', 'PILLOWS'], notes: 'One of a kind vintage rugs', login: null },
  { name: 'Regency Royale', website: null, showroomRep: 'SLC', tradeRetail: null, stockCustom: null, priceRange: null, offerings: ['RUGS'], notes: 'Area rug showroom', login: null },
  { name: 'The Citizenry', website: 'https://www.the-citizenry.com/', showroomRep: 'Online', tradeRetail: 'Retail', stockCustom: 'Stock', priceRange: 'Mid', offerings: ['PILLOWS', 'BEDDING'], notes: null, login: null },
  { name: 'Parachute Home', website: 'https://parachutehome.com/', showroomRep: 'Online\nNancy Anderson\nnanderson@parachutehome.com', tradeRetail: 'Retail', stockCustom: 'Stock', priceRange: 'Mid', offerings: ['BEDDING'], notes: null, login: null },
  { name: 'Lulu & Georgia', website: 'https://www.luluandgeorgia.com/', showroomRep: null, tradeRetail: 'Retail', stockCustom: null, priceRange: null, offerings: [], notes: null, login: null },
  { name: 'Maiden Home', website: 'https://maidenhome.com/', showroomRep: null, tradeRetail: 'Retail', stockCustom: null, priceRange: null, offerings: [], notes: null, login: null },
  { name: 'Zara Home', website: 'https://www.zarahome.com/us', showroomRep: null, tradeRetail: 'Retail', stockCustom: null, priceRange: 'Low', offerings: ['DECOR'], notes: null, login: null },
  { name: 'CB2', website: 'https://www.cb2.com/', showroomRep: 'Denver', tradeRetail: 'Retail', stockCustom: null, priceRange: null, offerings: [], notes: null, login: null },
  { name: 'Crate & Barrel', website: 'https://www.crateandbarrel.com/', showroomRep: 'SLC', tradeRetail: 'Retail', stockCustom: null, priceRange: null, offerings: [], notes: null, login: null },
  { name: 'Rejuvenation', website: 'https://www.rejuvenation.com/', showroomRep: 'SLC', tradeRetail: 'Retail', stockCustom: null, priceRange: null, offerings: [], notes: null, login: null },
  { name: 'Pottery Barn', website: 'https://www.potterybarn.com/', showroomRep: 'SLC', tradeRetail: 'Retail', stockCustom: null, priceRange: null, offerings: [], notes: null, login: null },
  { name: 'Williams Sonoma', website: 'https://www.williams-sonoma.com/', showroomRep: null, tradeRetail: 'Retail', stockCustom: null, priceRange: null, offerings: [], notes: 'Kitchen', login: null },
  { name: 'Cooper Classics', website: 'https://cooperclassics.com/', showroomRep: 'Online', tradeRetail: 'Trade', stockCustom: null, priceRange: null, offerings: ['MIRRORS'], notes: null, login: null },
  { name: 'Trouvaille Imports', website: 'https://www.trouvailleimports.com/', showroomRep: 'LA', tradeRetail: null, stockCustom: null, priceRange: null, offerings: ['OUTDOOR'], notes: 'Antique limestone planters\nIndoor live trees', login: null },
  { name: 'Stone Yard Inc', website: 'https://stoneyardinc.com/', showroomRep: 'Online', tradeRetail: null, stockCustom: null, priceRange: null, offerings: ['OUTDOOR'], notes: 'Planters', login: null },
  { name: '1stDibs', website: 'https://www.1stdibs.com/', showroomRep: 'Online', tradeRetail: null, stockCustom: null, priceRange: null, offerings: [], notes: 'Unique/Vintage', login: null },
  { name: 'Scout Design Stuido', website: 'https://www.scoutdesignstudio.com/', showroomRep: 'Online', tradeRetail: null, stockCustom: null, priceRange: null, offerings: ['DECOR'], notes: 'Unique/Vintage', login: null },
  { name: 'The Expert', website: 'https://www.theexpert.com/shop', showroomRep: 'Online', tradeRetail: null, stockCustom: null, priceRange: null, offerings: [], notes: 'Unique/Vintage', login: null },
  { name: 'Taschen', website: 'https://www.taschen.com/en/', showroomRep: 'Online', tradeRetail: null, stockCustom: null, priceRange: null, offerings: ['DECOR'], notes: 'Coffee table books', login: null },
  { name: 'Booth & Williams', website: 'https://boothandwilliams.com/', showroomRep: 'Online', tradeRetail: null, stockCustom: null, priceRange: null, offerings: ['DECOR'], notes: 'Books for bookshelves', login: null },
  { name: 'Assouline', website: 'https://www.assouline.com/', showroomRep: 'Online', tradeRetail: null, stockCustom: null, priceRange: null, offerings: ['DECOR'], notes: 'Coffee table books', login: null },
  { name: 'Afloral', website: 'https://www.afloral.com/', showroomRep: 'Online', tradeRetail: null, stockCustom: null, priceRange: null, offerings: ['DECOR'], notes: 'Faux Stems', login: null },
  { name: 'DW Silks', website: 'https://www.dwsilks.com/', showroomRep: null, tradeRetail: null, stockCustom: null, priceRange: null, offerings: ['DECOR'], notes: 'Faux Foliage', login: null },
  { name: 'Millcreek Manor', website: null, showroomRep: 'Millcreek, UT', tradeRetail: null, stockCustom: null, priceRange: null, offerings: ['DECOR'], notes: 'European Antiques', login: null },
];